export default {
  VALID_FORM: 'VALID_FORM',
  FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  LOAD_CACHED_COUNTRIES: 'LOAD_CACHED_COUNTRIES',
  SET_COUNTRY: 'SET_COUNTRY',
  FIELD_CHANGE: 'FIELD_CHANGE',
  FORM_ERROR: 'FORM_ERROR',
};
