export default {
  VALID_FORM: 'VALID_FORM',
  FETCH_COUNTRIES: 'FETCH_COUNTRIES',
  SET_COUNTRY: 'SET_COUNTRY',
  FIELD_CHANGE: 'FIELD_CHANGE',
  FORM_ERROR: 'FORM_ERROR',
  CACHE_FORM: 'CACHE_FORM',
};
